spring:
  datasource:
    url: "jdbc:mariadb://localhost:3306/election"
    username: "root"
    password: "root"
    driverclassName: "org.mariadb.jdbc.Driver"
  jpa:
    hibernate:
      ddl-auto: "create-drop"
logging:
  level:
    root: "INFO"
  pattern:
    level: "%X{logID} %5p"